import type { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3000';

  const routes = [
    '',
    '/services',
    '/services/medical-billing',
    '/services/medical-coding',
    '/services/revenue-cycle-management',
    '/services/denial-management',
    '/services/ar-management',
    '/services/credentialing',
    '/services/eligibility-verification',
    '/services/prior-authorization',
    '/services/payment-posting',
    '/services/medical-billing-audit',
    '/services/patient-billing',
    '/services/rcm-consulting',
    '/specialties',
    '/specialties/orthopedics',
    '/specialties/cardiology',
    '/specialties/dermatology',
    '/specialties/gastroenterology',
    '/specialties/neurology',
    '/specialties/pediatrics',
    '/specialties/internal-medicine',
    '/specialties/family-medicine',
    '/specialties/pain-management',
    '/specialties/physical-therapy',
    '/specialties/behavioral-health',
    '/specialties/radiology',
    '/specialties/urology',
    '/specialties/general-surgery',
    '/solutions',
    '/solutions/independent-practices',
    '/solutions/specialty-clinics',
    '/solutions/multi-provider-groups',
    '/solutions/aging-ar',
    '/solutions/denial-management',
    '/how-it-works',
    '/about',
    '/rcm-assessment',
    '/contact',
    '/resources',
    '/resources/blog',
    '/resources/faqs',
    '/resources/guides',
    '/faqs',
    '/case-studies',
    '/testimonials',
    '/privacy-policy',
    '/terms',
    '/cookie-policy',
    '/accessibility',
  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: 'weekly' as const,
    priority: route === '' ? 1 : 0.8,
  }));
}
